### ISSUE TITLE
how to use links/URLs in the Microsoft chat bot.

### ISSUE THREAD

**Issue by sasmitasahu** [MicrosoftDocs/bot-framework-docs#103]
How to use links/URLs in the Microsoft chat bot. i want to use a website URL in my chat bot and on clicking on the URL it should be redirected to the browser. i am using C# for coding &  LUIS for language intent. I am new to MS bot framework. Can someone give me the some knowledge how it could be done.

**Comment by itvignes09** [comment]
session.send("[google](https://www.google.co.in)");

**Comment by sasmitasahu** [comment]
Thanks ! 
Can you please describe me in brief how to use the above code. following is my code what i am using currently. 

In Message Controller:
public class MessagesController : ApiController
    {
        /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                //await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
                await Conversation.SendAsync(activity, MakeLuisDialog);
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }
        internal static IDialog<UserEnquiry> MakeLuisDialog()
        {
            return Chain.From(() => new LUISDIalog(UserEnquiry.BuildForm));
        }

        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
    }
}

UserEnquiry.cs
------------------------
namespace BikeHaggleChatBot.Model
{
   
    public enum Actions
    {
        BikeAdSearch,
        BikeAdPost
    }   
    public enum BikeTypeOptions
    {
        Make,
        Model,
        BikeName
    }
    public enum AmmenitiesOptions
    {
        Bikes,
        PartNAccesories   
    }
    [Serializable]
    public class UserEnquiry
    {
        [Prompt("What action do you want to perform? {||}")]
        public Actions? ActionType;
        [Prompt("please select a keyword to search bikes? {||}")]
        public BikeTypeOptions? BikeOption;
        public List<AmmenitiesOptions> Ammenities;       

        public static IForm<UserEnquiry> BuildForm()
        {
            return new FormBuilder<UserEnquiry>()
            .Message("Welcome to the BikeHaggle bot!")
            .Build();
        }
    }
}

Luis Dialog.cs
-----------------------------

public class LUISDIalog : LuisDialog<UserEnquiry>
    {

        //RestaurantChatBot.MessagesController msg = new RestaurantChatBot.MessagesController();

        private readonly BuildFormDelegate<UserEnquiry> BikeSale;
        private object bot;
        private readonly object session;

        public LUISDIalog(BuildFormDelegate<UserEnquiry> BikeDetails)
        {
            this.BikeSale = BikeDetails;
        }
        [LuisIntent("")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            await context.PostAsync("I'm sorry I don't know what you mean.");
            context.Wait(MessageReceived);
        }
        [LuisIntent("Greetings")]
        public async Task Greetings(IDialogContext context, LuisResult result)
        {
            context.Call(new RootDialog(), Callback);
        }
        private async Task Callback(IDialogContext context, IAwaitable<object> result)
        {
            context.Wait(MessageReceived);
        }
        [LuisIntent("Search")]
        public async Task Searchbike(IDialogContext context, LuisResult result)  //result out put
        {
            var enrollmentForm = new FormDialog<UserEnquiry>(new UserEnquiry(),
           this.BikeSale, FormOptions.PromptInStart);
            context.Call<UserEnquiry>(enrollmentForm, Callback);
        }
        [LuisIntent("AvailableAmenities")]
        public async Task QueryAmenities(IDialogContext context, LuisResult result)
        {
            foreach (var entity in result.Entities.Where(Entity => Entity.Type == "Amenities"))
            {
                var value = entity.Entity.ToLower();
                if (value == "banquet" || value == "pool" || value == "garden" ||
                value == "kidszone" || value == "yamaha")
                {
                    await context.PostAsync("Yes, We have that.");
                    context.Wait(MessageReceived);
                    return;

                }
                else
                {
                    await context.PostAsync("I'm sorry we don't have that.");
                    context.Wait(MessageReceived);
                    return;
                }
            }
            await context.PostAsync("I'm sorry we don't have that.");
            context.Wait(MessageReceived);
            return;
        }
    }


Root Dialog.cs
-----------------------------
 [Serializable]
    public class RootDialog : IDialog<object>
    {
        public async Task StartAsync(IDialogContext context)
        {
            await context.PostAsync("Hi, I am from BikeHaggle Crew");
            await Respond(context);
            context.Wait(MessageReceivedAsync);
        }

        private static async Task Respond(IDialogContext context)
        {
            var userName = string.Empty;
            context.UserData.TryGetValue<string>("CName",out userName);
            if(string.IsNullOrEmpty(userName))
            {
                await context.PostAsync("What is your name?");
                context.UserData.SetValue<bool>("GetName", true);
            }
            else
            {
                await context.PostAsync(string.Format("Hi {0}. How can we help you today?", userName));
            }
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            //var activity = await result as Activity;

            //// calculate something for us to return
            //int length = (activity.Text ?? string.Empty).Length;

            //// return our reply to the user
            //await context.PostAsync($"You sent {activity.Text} which was {length} characters");

            //context.Wait(MessageReceivedAsync);
            var message = await argument;
            var userName = String.Empty;
            var getName = false;
            context.UserData.TryGetValue<string>("CName", out userName);
            context.UserData.TryGetValue<bool>("GetName", out getName);
            if (getName)
            {
                userName = message.Text;
                context.UserData.SetValue<string>("CName", userName);
                context.UserData.SetValue<bool>("GetName", false);
            }
            await Respond(context);
            context.Done(message);
        }
    }

**Comment by Kaiqb** [comment]
This might help you: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-media-attachments
