### ISSUE TITLE
Web App Bot Skype Channel stuck inReview

### ISSUE THREAD

**Issue by semicolon87** [MicrosoftDocs/bot-framework-docs#105]
**Bot Info:**

- Bot handle: LarcAI_HRBot20180114
- App ID: 5a71914b-03b9-44dc-801c-2a4bdc565d50
- SDK Platform: .NET
- SDK Version: 3.12.2.4 (Microsoft.Bot.Builder)
- Active Channels: Skype
- Deployment Environment: VS2017 - Azureweb

Hello,

I have had my Skype channel "inReview" for weeks now.
I would just like to know how you test the Skype channel as well as how I can have this review process expedited?

The bot works on ngrok emulator using the enpoints as well as on the Test Web app interface on Azure.
If I send a message to the bot on skype, the message is sent, but the bot does not reply.
On Azure statistics it shows the messages as received.

I have attached a few pictures.

Please advise?

Thank you.
![1](https://user-images.githubusercontent.com/20204089/35566840-86f82a1e-05cb-11e8-8b7d-7d21b7dadca4.PNG)
![2](https://user-images.githubusercontent.com/20204089/35566842-87303dd2-05cb-11e8-95e6-1633ec60275a.PNG)
![3](https://user-images.githubusercontent.com/20204089/35566843-876c0678-05cb-11e8-9cb9-87c408310f2f.PNG)
![5](https://user-images.githubusercontent.com/20204089/35566844-87a9795e-05cb-11e8-9c0a-0a9ab5e83780.PNG)
![6](https://user-images.githubusercontent.com/20204089/35566845-87e7be94-05cb-11e8-9cda-b80a69fcc153.PNG)

**Comment by semicolon87** [comment]
Edited post to include Bot Info.

**Comment by AkshayKanchan** [comment]
Hi, I am facing the same issue, typically how much time a chatbot for Skype should take to get reviewed and release? I have submitted a chatbot to Skype for review it's been a week, the bot is still "inReview" and I haven't received any emails from Skype yet. Also the same case with Bing channel

Chatbot Info
Microsoft App ID : 77471931-f49d-4501-8755-3ca5fbffc08e
Submitted For Review : Skype, Bing.
Deployment Environment : Azure Bot Service.

**Comment by semicolon87** [comment]
Hi,

Yeah mine is STILL in review, its been over a month now?

I got around this by just using the direct channel,

Have you added the bot to your directory in slype?

Try characters like a space and a “.” Then the message.
This worked for me on skype Preview.

**Comment by Kaiqb** [comment]
@semicolon87 @AkshayKanchan 
- Adding @rahul-microsoft regarding skype review. 
- For support, please use: https://stackoverflow.com/questions/tagged/botframework or https://gitter.im/Microsoft/BotBuilder.
