### ISSUE TITLE
Sample code and document conflict in JavaScript

### ISSUE THREAD

**Issue by akiyoshi** [MicrosoftDocs/bot-framework-docs#151]
Because the sample response is the same as the .NET one, there is a conflict between the code and document. The exact response should be **0: You said "Hi"**

Since Turn is explained in the next step, I think it is better to modify the sample code.

https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0#explore-code

**Comment by Kaiqb** [comment]
Minor. Won't fix.
