### ISSUE TITLE
Incorrect instructions in getting started tutorial for .NET v4

### ISSUE THREAD

**Issue by amthomas46** [MicrosoftDocs/bot-framework-docs#167]
You don't have to create a new bot configuration in the emulator. You can simply click "Open bot" and navigate to the .bot file that is created when you use the template

https://github.com/MicrosoftDocs/bot-framework-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md

**Comment by Kaiqb** [comment]
For this example, it works either way.
