### ISSUE TITLE
Translation Sample in the SDK missing?

### ISSUE THREAD

**Issue by n01d** [MicrosoftDocs/bot-framework-docs#173]
The text mentions a samlple in the SDK that I can't find? A link should be added or the comment beein removed.

> !TIP] See the Translation sample in the SDK for a sample bot that implements callbacks for detecting and changing the user language.

https://github.com/MicrosoftDocs/bot-framework-docs/blob/live/articles/v4sdk/bot-builder-howto-translation.md

**Comment by Kaiqb** [comment]
@n01d - the sample was removed from the SDK. We'll update the tip in the topic. Thanks
