### ISSUE TITLE
 _supportedLanguages

### ISSUE THREAD

**Issue by n01d** [MicrosoftDocs/bot-framework-docs#174]
_supportedLanguages in one of the C# code samples is not defined or I can find the right piece of code.

```
public static bool IsSupportedLanguage(string language) =>
        _supportedLanguages.Contains(language);
```

https://github.com/MicrosoftDocs/bot-framework-docs/blob/live/articles/v4sdk/bot-builder-howto-translation.md

**Comment by Kaiqb** [comment]
Added to backlog for investigation.
