### ISSUE TITLE
LUIS Intent

### ISSUE THREAD

**Issue by thebeebs** [MicrosoftDocs/bot-framework-docs#32]
The [document](https://github.com/Microsoft/bot-framework-docs/blob/master/articles/nodejs/bot-builder-nodejs-recognize-intent.md) suggests that you use TriggerActions to match LUIS intents. However, if you do thi,s then even if you are in a dialog, if an intent match happens then you will be sent off to a different dialog. Also LUIS will be called with every interaction, even if you are in a dialog.

Instead you should use an IntentDialog with a LUIS recogniser, Otherwise issues can arise:

In the last hack I ran both of the teams using node followed this documentation and both had issues. One team for example had two intents in Luis "Book a holiday" and "Book a course". If the user was pointed to the "Book a course" dialog they would be asked a questions: 

1. How old are you. Next they would be asked: 
2. Which Country are you coming from. The user could enter any country. But if they entered "Russia" then an exception would be thrown. 

We traced the issue back to the triggerMethod in this documentation. What was happening was that even though the user was in a dialog, LUIS was being called every time a user responded. If an intent is matched it will try and route you to a correct dialog. In the instance above, LUIS had incorrectly tagged "Russia" as an intent for "Book a Holiday" so it then tries to forward the user on  to the Book a course dialog (This fails also because you are already in a dialog).

Of the 2 node teams at our hack both had this same bug. We switched both of them over to using a LUIS recogniser and it solved the issue.

Is it ok for me to go a head and make a pull request containing documentation on how to do LUIS with a recogniser.

**Comment by RobStand** [comment]
@thebeebs This is good feedback. Please submit a PR and I'll ask our LUIS expert to review. Thanks very much for your contribution!
