### ISSUE TITLE
acces service bot without the API 

### ISSUE THREAD

**Issue by bethpet** [MicrosoftDocs/bot-framework-docs#55]
Hi, I cannot find on documentation if is it possible to call the service bot without to use the line direct connector and without to use the BotFramework. Can you help me?

thank you.

**Comment by mostafafmamo** [comment]
![picsart_10-04-12 59 49](https://user-images.githubusercontent.com/32531311/31213607-21ebf140-a9b0-11e7-962d-6ea602d21d31.jpg)

**Comment by RobStand** [comment]
We don't have documentation on how to do this.
