### ISSUE TITLE
The last entry in the SAN list takes precedence over SN

### ISSUE THREAD

**Issue by bogdan-mabo** [MicrosoftDocs/bot-framework-docs#59]
The documentation should make this clear.
Please see:
[https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling/issues/2#issuecomment-303771297](url)

**Comment by Kaiqb** [comment]
Issue #2 has been closed in the samples repo.(https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling).
