### ISSUE TITLE
The "Feedback, comments, and support" link in contributor-guide-index.md is broken

### ISSUE THREAD

**Issue by sphanley** [MicrosoftDocs/bot-framework-docs#60]
The last link in the [General Guidance](https://github.com/MicrosoftDocs/bot-framework-docs/blob/live/contributor-guide/contributor-guide-index.md#general-guidance) section of contributer-guide-index.md, which reads "Feedback, comments, and support", is dead and leads to a 404 page.

**Comment by RobStand** [comment]
Fixed. Thanks. Not sure where that should go so I just removed it.
