### ISSUE TITLE
Lack of Information under Submit Credentials

### ISSUE THREAD

**Issue by deadandhallowed** [MicrosoftDocs/bot-framework-docs#74]
View page [Channel Connect GroupMe](https://docs.microsoft.com/en-us/bot-framework/channel-connect-groupme).
Under "Submit credentials," it says

> On dev.botframework.com, paste the client_id value you just copied into the Client ID field. Paste the Access Token value into the Access Token field.

Where are these fields on dev.botframework.com? More information may be needed.

**Comment by RobStand** [comment]
Thanks @deadandhallowed. We'll work on an update for this.

**Comment by RobStand** [comment]
No longer applicable. We'll have an update in the new release.
