### ISSUE TITLE
My Bots page renders with not correct alignment [Chrome Canary]

### ISSUE THREAD

**Issue by alundiak** [MicrosoftDocs/bot-framework-docs#89]
Here is when I log in, and look to the list of my bots:
<img width="1440" alt="my_bots_page_1" src="https://user-images.githubusercontent.com/2131633/33798095-18c29e84-dd13-11e7-936d-d64728db1f5f.png">

And when I click first time of some bot to see its settings, I see the page layout this way:
<img width="1440" alt="my_bots_page_2" src="https://user-images.githubusercontent.com/2131633/33798100-2cac589a-dd13-11e7-9109-a12ece5ba4e6.png">

Meaning, that page shows first ok, half of second, and then left section of page is partially hidden - shifted to the hidden left side (margin/padding/etc), and on right section appears vertical scrollbar.

This was since **MacOS Sierra on Chrome Canary** (64.0.3282.3, 65.0.3289.0). Cache cleared, zoom cleared, `chrome://flags` reset to default. `html` tag size is 1436x262.

btw, in web console, I see 2 requests failed, not sure if it's related:
<img width="1430" alt="screen shot 2017-12-09 at 19 12 26" src="https://user-images.githubusercontent.com/2131633/33798254-865464a8-dd15-11e7-88e0-98380299b0e6.png">

full logs:
[dev.botframework.com-1512843158694.log](https://github.com/MicrosoftDocs/bot-framework-docs/files/1544955/dev.botframework.com-1512843158694.log)

But on regular Chrome (62.0.3202.94), there is no such issue (1400x530).
There is no issue on Safrai 11.0.1 (13604.3.5).

**Comment by Kaiqb** [comment]
@alundiak - for support, use: https://stackoverflow.com/questions/tagged/botframework.
