### ISSUE TITLE
IP range for Bot Framework Connector

### ISSUE THREAD

**Issue by kzuenkler-avanade** [MicrosoftDocs/bot-framework-docs#90]
For a hybrid topology with the bot running on-prem I need the range of IP addresses to be allowed on the client's firewall for the incoming connections. I did not find a documentation about this range (per Microsoft Datacenter region).

**Comment by Kaiqb** [comment]
@kzuenkler-avanade you can find the Azure Datacenter IP range here: https://www.microsoft.com/en-us/download/details.aspx?id=41653.
